language: node_js
node_js: 11.10.0
cache:
  yarn: true
  directories:
    - node_modules
warnings_are_errors: false
install:
  - yarn install
  - yarn global add firebase-tools
script:
  - yarn run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
