name: Yarn package

env:
  IMAGE: nailyav/innometrics:latest
  DOKKU_APP_URL: 'ssh://dokku@851.250.3.9/diplome'

on: [push]

jobs:
  yarn_build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 10.x ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
          cache: npm
      - name: clean cache
        run: yarn cache clean
      # - name: browser list
      #   run: npx browserslist@latest --update-db
      - name: Install dependencies
        run: npm install #--legacy-peer-deps --force # npm install --legacy-peer-depsarc 
      - name: Test by Jest
        run: yarn test
        continue-on-error: true

  production:
      needs: [ "yarn_build" ]
      name: Push Docker image to Docker Hub
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cache Docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

        - uses: docker-practice/actions-setup-docker@master
          with:
            docker_version: 20.10
            docker_channel: stable

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: nailyav
            password: dckr_pat_D7BCX9D9vTOAGgyvf9kHvkcyeJM

        - name: Build and push
          # uses: mr-smithers-excellent/docker-build-push@v4
          uses: docker/build-push-action@v2
          with:
            context: .
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ env.IMAGE }}
            cache-from: type=registry,ref=nailyav/innometrics:buildcache
            cache-to: type=registry,ref=nailyav/innometrics:buildcache,mode=max

  push_to_dokku:
    name: Push to Dokku
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Push to dokku
        uses: dokku/github-action@main
        with:
          git_remote_url: ${{ env.DOKKU_APP_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.IMAGE }}
            