name: Yarn package

on: [push]

jobs:
  yarn_build:

    runs-on: self-hosted
      
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm install yarn -g
          yarn
          yarn test
        continue-on-error: true

  production:
      needs: [ "yarn_build" ]
      name: Push Docker image to Docker Hub
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cache Docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: nailyav
            password: dckr_pat_D7BCX9D9vTOAGgyvf9kHvkcyeJM

        - name: Build and push
          # uses: mr-smithers-excellent/docker-build-push@v4
          uses: docker/build-push-action@v2
          with:
            context: .
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: nailyav/innometrics:latest
            cache-from: type=registry,ref=nailyav/innometrics:buildcache
            cache-to: type=registry,ref=nailyav/innometrics:buildcache,mode=max

        - name: Start container
          run: yarn start

            